In [172]:
import pandas as pd

In [173]:
students = {
    "Name": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Mariam"],
    "Age": [20, 21, 19, 22, 20, 21],
    "Grade": [85, 92, 78, 95, 88, 73],
    "Department": ["CS", "AI", "CS", "DS", "AI", "DS"]
}
df = pd.DataFrame(students)

In [174]:
#2
df.iloc[0:3]

   Name  Age  Grade Department
0   Ali   20     85         CS
1  Sara   21     92         AI
2  Omar   19     78         CS

In [175]:
df.iloc[-2:]

      Name  Age  Grade Department
4  Youssef   20     88         AI
5   Mariam   21     73         DS

In [176]:
df.shape

(6, 4)

In [177]:
df.columns

Index(['Name', 'Age', 'Grade', 'Department'], dtype='str')

In [178]:
df.dtypes

Name            str
Age           int64
Grade         int64
Department      str
dtype: object

In [179]:
#shape returns a tuple of the dimensions of the dataframe (number of rows , number of columns)
#size returns an integer of the total number of elemets in dataframe
#len(df) returns an integer of the number of rows

In [180]:
#3
df["Name"]

0        Ali
1       Sara
2       Omar
3       Lina
4    Youssef
5     Mariam
Name: Name, dtype: str

In [181]:
df[["Name","Grade"]]

      Name  Grade
0      Ali     85
1     Sara     92
2     Omar     78
3     Lina     95
4  Youssef     88
5   Mariam     73

In [182]:
df.iloc[0:2]

   Name  Age  Grade Department
0   Ali   20     85         CS
1  Sara   21     92         AI

In [183]:
df.loc[0:2,'Grade']

0    85
1    92
2    78
Name: Grade, dtype: int64

In [184]:
filt = df["Grade"] > 85
df.loc[filt]

      Name  Age  Grade Department
1     Sara   21     92         AI
3     Lina   22     95         DS
4  Youssef   20     88         AI

In [185]:
filt = df["Department"] == "AI"
df.loc[filt]

      Name  Age  Grade Department
1     Sara   21     92         AI
4  Youssef   20     88         AI

In [186]:
filt = df['Grade'] >=60
df.loc[filt,'Passed'] = "Yes"
filt = ~(df['Grade'] >= 60)
df.loc[filt,'Passed'] = "No"

In [187]:
df

      Name  Age  Grade Department Passed
0      Ali   20     85         CS    Yes
1     Sara   21     92         AI    Yes
2     Omar   19     78         CS    Yes
3     Lina   22     95         DS    Yes
4  Youssef   20     88         AI    Yes
5   Mariam   21     73         DS    Yes

In [188]:
filt = df['Grade'] >= 90
df.loc[filt,'Grade_Level'] = "Excellent"
filt =  (df['Grade'] >=80) & (df['Grade'] < 90) 
df.loc[filt,'Grade_Level'] = "Good"
filt = ~(df['Grade'] >=80)
df.loc[filt,'Grade_Level'] = "Average"

In [189]:
df

      Name  Age  Grade Department Passed Grade_Level
0      Ali   20     85         CS    Yes        Good
1     Sara   21     92         AI    Yes   Excellent
2     Omar   19     78         CS    Yes     Average
3     Lina   22     95         DS    Yes   Excellent
4  Youssef   20     88         AI    Yes        Good
5   Mariam   21     73         DS    Yes     Average

In [190]:
df.replace((df.loc[2,'Department']),"AI",inplace=True)

      Name  Age  Grade Department Passed Grade_Level
0      Ali   20     85         AI    Yes        Good
1     Sara   21     92         AI    Yes   Excellent
2     Omar   19     78         AI    Yes     Average
3     Lina   22     95         DS    Yes   Excellent
4  Youssef   20     88         AI    Yes        Good
5   Mariam   21     73         DS    Yes     Average

In [191]:
df

      Name  Age  Grade Department Passed Grade_Level
0      Ali   20     85         AI    Yes        Good
1     Sara   21     92         AI    Yes   Excellent
2     Omar   19     78         AI    Yes     Average
3     Lina   22     95         DS    Yes   Excellent
4  Youssef   20     88         AI    Yes        Good
5   Mariam   21     73         DS    Yes     Average

In [192]:
df["Grade"].mean()

np.float64(85.16666666666667)

In [193]:
df["Grade"].max()

np.int64(95)

In [194]:
df["Grade"].min()

np.int64(73)

In [195]:
index=df.index[df["Grade"]==df["Grade"].max()]
df.iloc[index]

   Name  Age  Grade Department Passed Grade_Level
3  Lina   22     95         DS    Yes   Excellent

In [196]:
grp = df.groupby("Department")
grp.get_group("AI")["Age"].mean()

np.float64(20.0)

In [197]:
grp.get_group("DS")["Age"].mean()

np.float64(21.5)

In [198]:
df["Department"].value_counts()

Department
AI    4
DS    2
Name: count, dtype: int64

In [199]:
df_new = df.loc[df['Grade'] > 80, ["Name", "Grade", "Department"]].sort_values('Grade',ascending=False)

In [ ]:
df_new
##########################

      Name  Grade Department
3     Lina     95         DS
1     Sara     92         AI
4  Youssef     88         AI
0      Ali     85         AI

In [ ]:
#7
data = {
    "Name": ["Ali", "Sara", None, "Lina"],
    "Age": [20, None, 19, 22],
    "Grade": [85, 92, 78, None]
}
df_missing = pd.DataFrame(data)

In [202]:
df_missing.isna()

    Name    Age  Grade
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True

In [203]:
df_missing.isna().sum()

Name     1
Age      1
Grade    1
dtype: int64

In [204]:
(df_missing.isna().sum()).sum()

np.int64(3)

In [205]:
df_missing.loc[df_missing['Name'].isna(), 'Name'] = "Unknown"

In [206]:
df_missing

      Name   Age  Grade
0      Ali  20.0   85.0
1     Sara   NaN   92.0
2  Unknown  19.0   78.0
3     Lina  22.0    NaN

In [212]:
df_missing.loc[df_missing['Age'].isna(), 'Age'] = df_missing['Age'].mean()
df_missing.loc[df_missing['Grade'].isna(), 'Grade'] = df_missing['Grade'].mean()

In [ ]:
df_missing
#########################################

      Name        Age  Grade
0      Ali  20.000000   85.0
1     Sara  20.333333   92.0
2  Unknown  19.000000   78.0
3     Lina  22.000000   85.0

In [ ]:
#8
students_info = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Ali", "Sara", "Omar", "Lina"],
    "Department": ["CS", "AI", "CS", "DS"]
})

students_grades = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Grade": [85, 92, 78, 95]
})

In [ ]:
both=pd.merge(students_info,students_grades,on="ID")
both

   ID  Name Department  Grade
0   1   Ali         CS     85
1   2  Sara         AI     92
2   3  Omar         CS     78
3   4  Lina         DS     95

In [247]:
#9
new_students = pd.DataFrame({
    "ID": [5, 6],
    "Name": ["Youssef", "Mariam"],
    "Department": ["AI", "DS"]
})
both=pd.concat([both,new_students],axis=0,)

In [ ]:
both
################################

   ID     Name Department  Grade
0   1      Ali         CS   85.0
1   2     Sara         AI   92.0
2   3     Omar         CS   78.0
3   4     Lina         DS   95.0
0   5  Youssef         AI    NaN
1   6   Mariam         DS    NaN

In [275]:
#10
grp1 = both.groupby("Department")
grp["Grade"].mean()

Department
AI    92.0
CS    81.5
DS    95.0
Name: Grade, dtype: float64

In [286]:
top = grp["Grade"].mean().idxmax()
top

'DS'

In [287]:
both.to_csv('both.csv', index=False)